#include "../include/rendering.h"
#include <string>

namespace CarGame {

Renderer::Renderer() {
    // Default constructor - model is initialized in initialize()
}

Renderer::~Renderer() {
    // Clean up resources
    UnloadModel(carModel);
}

void Renderer::initialize(const Car& car) {
    // Create the car model (a simple box) using the car's config properties
    carModel = LoadModelFromMesh(GenMeshCube(
        car.config.width, 
        car.config.height, 
        car.config.length
    ));
}

// Draws the 3D scene, including the floor and the car, and overlays UI text
void Renderer::drawScene(const GameCamera& camera, const Car& car, const Vector3& floorPosition) {
    BeginMode3D(camera.getCamera());
        // Draw the ground plane
        DrawPlane(floorPosition, Vector2{50.0f, 50.0f}, LIGHTGRAY);
        
        // Draw the car model with the correct rotation (converted from radians to degrees)
        DrawModelEx(carModel, car.position, 
                    Vector3{0.0f, 1.0f, 0.0f}, 
                    car.rotation * RAD2DEG, 
                    Vector3{1.0f, 1.0f, 1.0f}, 
                    MAROON);
    EndMode3D();

    // Get screen dimensions
    int screenWidth = GetScreenWidth();
    int textX = screenWidth - 400;  // Position text on right side
    int textY = 20;                 // Start from the top with some margin
    int lineHeight = 24;            // Space between lines
    int fontSize = 20;
    Color textColor = BLACK;
    
    // Draw a semi-transparent panel for better readability
    DrawRectangle(textX - 10, textY - 10, 310, 560, ColorAlpha(LIGHTGRAY, 0.7f));
    
    // Display Car Information - Section Title
    DrawText("CAR TELEMETRY", textX, textY, fontSize, DARKBLUE);
    textY += lineHeight + 5;
    
    // Vehicle Motion
    DrawText("MOTION", textX, textY, fontSize - 4, DARKGRAY);
    textY += lineHeight;
    DrawText(TextFormat("Speed: %.2f km/h", car.speed * 3.6f), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Rotation: %.2f°", car.rotation * RAD2DEG), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Position: (%.1f, %.1f, %.1f)", 
             car.position.x, car.position.y, car.position.z), textX, textY, fontSize, textColor);
    textY += lineHeight;
    
    // Engine Data
    textY += 5;
    DrawText("ENGINE", textX, textY, fontSize - 4, DARKGRAY);
    textY += lineHeight;
    DrawText(TextFormat("Engine Speed: %.0f RPM", car.engineSpeed), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Engine Torque: %.1f Nm", 
             car.getEngineTorque(car.throttle, car.engineSpeed)), textX, textY, fontSize, textColor);
    textY += lineHeight;
    
    // Controls
    textY += 5;
    DrawText("CONTROLS", textX, textY, fontSize - 4, DARKGRAY);
    textY += lineHeight;
    DrawText(TextFormat("Throttle: %.2f", car.throttle), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Brake: %.2f", car.brake), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Steering Angle: %.2f°", car.steeringAngle * RAD2DEG), textX, textY, fontSize, textColor);
    textY += lineHeight;
    
    // Physics Data
    textY += 5;
    DrawText("PHYSICS", textX, textY, fontSize - 4, DARKGRAY);
    textY += lineHeight;
    DrawText(TextFormat("Accel X: %.2f m/s²", car.acceleration.x), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Velocity X: %.2f m/s", car.velocity.x), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Velocity Z: %.2f m/s", car.velocity.z), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Slip Ratio: %.3f", car.slipRatio), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Force Generated by Wheels: %.2f N", car.longitudinalForce), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Net Force on Car Body: %.2f N", car.netForce), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Drag Force: %.2f N", car.dragForce), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Rolling Resistance: %.2f N", car.rollingResistance), textX, textY, fontSize, textColor);

    textY += lineHeight;
    DrawText(TextFormat("Lateral Velocity: %.2f m/s", car.lateralVelocity), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Yaw Rate: %.2f rad/s", car.yawRate), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Slip Angle Front: %.2f°", car.slipAngleFront * RAD2DEG), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Slip Angle Rear: %.2f°", car.slipAngleRear * RAD2DEG), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Lateral Force Front: %.2f N", car.lateralForceFront), textX, textY, fontSize, textColor);
    textY += lineHeight;
    DrawText(TextFormat("Lateral Force Rear: %.2f N", car.lateralForceRear), textX, textY, fontSize, textColor);
    
    // Draw instructions at the bottom left
    DrawText("Controls: Arrow Keys - Up (throttle), Down (brake), Left/Right (steering)", 20, GetScreenHeight() - 40, 20, DARKGRAY);
    DrawText("Press ESC to exit", 20, GetScreenHeight() - 20, 20, DARKGRAY);
}

} // namespace CarGame